sonar.verbose=true
sonar.organization=navya01-firstkey
sonar.projectkey=navya01-firstkey_navyatrend
sonar.projectname=navyatrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
